send:
  description: Sends RCSwitch code
  fields:
    code:
      description: Code to send
      example: 1234567
register:
  description: Register RCSwitch code
  fields:
    code:
      description: Code to register
      example: 1234567
forget:
  description: Forget RCSwitch code
  fields:
    code:
      description: Code to forget
      example: 1234567
learn:
  description: Starts sensor learn for 30 seconds
list:
  description: Dumps sensor's learned codes
